CREATE TABLE `sfm_ta_product` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `prd_id` varchar(20) NOT NULL DEFAULT '' COMMENT '产品编码',
  `prd_code` varchar(20) NOT NULL DEFAULT '' COMMENT '产品代码',
  `model_flag` varchar(1) NOT NULL DEFAULT '0' COMMENT '0-正常产品,1-测试产品',
  `prd_cyclical_type` varchar(1) NOT NULL DEFAULT '0' COMMENT '产品周期形态:1-封闭型 2-开放型 3-产品周期型 4-客户周期型',
  `ta_code` varchar(9) NOT NULL DEFAULT '' COMMENT 'TA代码',
  `prd_name` varchar(64) NOT NULL DEFAULT '' COMMENT '产品名称',
  `prd_short_name` varchar(256) NOT NULL DEFAULT '' COMMENT '产品简称',
  `interest_way` varchar(1) NOT NULL DEFAULT '0' COMMENT '0-净值类1-货币式收益类2-预期收益类',
  `nav` decimal(20,9) NOT NULL DEFAULT '0.000000000' COMMENT '产品净值',
  `tot_nav` decimal(20,9) NOT NULL DEFAULT '0.000000000' COMMENT '产品累计净值',
  `nav_date` int(11) NOT NULL DEFAULT '0' COMMENT '净值日期',
  `face_value` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '产品面值',
  `iss_price` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '发行价格',
  `prd_benchmark` varchar(8) NOT NULL DEFAULT '' COMMENT '业绩比较基准',
  `prd_sponsor` varchar(3) NOT NULL DEFAULT '' COMMENT '产品发起人',
  `prd_trustee` varchar(3) NOT NULL DEFAULT '' COMMENT '产品托管人',
  `prd_manager` varchar(16) NOT NULL DEFAULT '' COMMENT '产品管理人',
  `branch_no` varchar(16) NOT NULL DEFAULT '' COMMENT '产品主办机构',
  `dep_id` varchar(16) NOT NULL DEFAULT '' COMMENT '产品主办部门',
  `ipo_start_date` int(11) NOT NULL DEFAULT '0' COMMENT '募集开始日期',
  `ipo_end_date` int(11) NOT NULL DEFAULT '0' COMMENT '募集结束日期',
  `estab_date` int(11) NOT NULL DEFAULT '0' COMMENT '产品成立日期',
  `lock_up_days` int(11) NOT NULL DEFAULT '0' COMMENT '锁定期',
  `begin_of_lock` varchar(1) DEFAULT '0' COMMENT '锁定期开始日类型 0-交易确认日 1-交易导出日',
  `income_start_date` int(11) NOT NULL DEFAULT '0' COMMENT '收益开始日期',
  `income_end_date` int(11) NOT NULL DEFAULT '0' COMMENT '收益到期日期',
  `end_date` int(11) NOT NULL DEFAULT '0' COMMENT '结束日期',
  `alimit_end_date` int(11) NOT NULL DEFAULT '0' COMMENT '募集后封闭到期日',
  `ipo_time` int(11) NOT NULL DEFAULT '0' COMMENT '募集开始时间',
  `real_estab_date` int(11) NOT NULL DEFAULT '0' COMMENT '实际成立日期',
  `prd_min_bala` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '产品最低募集金额',
  `prd_max_bala` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '产品最高募集金额',
  `p_min_bala` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '个人募集最低投资金额',
  `p_max_bala` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '个人募集最高投资金额',
  `prd_issue_real_bala` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '产品实际募集金额',
  `div_modes` varchar(8) NOT NULL DEFAULT '' COMMENT '允许的分红方式',
  `div_mode` varchar(1) NOT NULL DEFAULT '' COMMENT '分红方式',
  `rec_per_liqui_mode` varchar(1) NOT NULL DEFAULT '' COMMENT '募集期划转模式 0-未扣款 1-每日扣款',
  `open_per_liqui_mode` varchar(2) NOT NULL DEFAULT '0' COMMENT '开放期划转模式 0-系统1-手工',
  `buy_accounting_type` varchar(1) NOT NULL DEFAULT '0' COMMENT '申购账务模式 0-不撤单 1-撤单',
  `withdraw_mode` varchar(1) NOT NULL DEFAULT '0' COMMENT '赎回模式',
  `channels` varchar(50) NOT NULL DEFAULT '' COMMENT '允许渠道[0-柜台1-柜面交易2-网上银行3-自助终端4-电话银行5-ATM6-手机银行7-其他',
  `client_groups` varchar(20) NOT NULL DEFAULT '' COMMENT '允许客户组',
  `control_flag` varchar(250) NOT NULL DEFAULT '0011' COMMENT '控制标志',
  `sub_exp` varchar(1) NOT NULL DEFAULT '0' COMMENT '认购导出模式',
  `risk_level` varchar(1) NOT NULL DEFAULT '0' COMMENT '风险等级',
  `prd_status` varchar(1) NOT NULL DEFAULT '' COMMENT '产品状态',
  `conv_flag` varchar(1) NOT NULL DEFAULT '' COMMENT '转换标志',
  `prd_total` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '产品当前总份额',
  `curr_type` varchar(3) NOT NULL DEFAULT '' COMMENT '币种',
  `cash_flag` varchar(1) NOT NULL DEFAULT '' COMMENT '钞汇标志',
  `open_time` int(11) NOT NULL DEFAULT '0' COMMENT '开市时间',
  `close_time` int(11) NOT NULL DEFAULT '0' COMMENT '闭市时间',
  `first_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '个人首次最低投资金额',
  `papp_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '个人追加最低投资金额',
  `pminimum_holding_vol` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '个人最低持有份额',
  `pmaximum_holding_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '个人最大持有金额',
  `holding_limit_type` int(11) DEFAULT '2' COMMENT '持有限制类型 1-产品 2-客户',
  `ofirst_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '机构首次最低投资金额',
  `oapp_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '机构追加最低投资金额',
  `ominimum_holding_vol` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '机构最低持有份额',
  `omaximum_holding_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '机构最大持有金额',
  `buy_unit_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '最小购买单位',
  `withdraw_unit_amt` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '最小赎回单位',
  `prd_current_quota` decimal(32,8) NOT NULL DEFAULT '0.00000000' COMMENT '产品本期限额',
  `debit_account` varchar(32) NOT NULL DEFAULT '' COMMENT '实时赎回垫资账号',
  `crebit_cust_id` bigint(20) NOT NULL COMMENT '赎回账号客户号',
  `crebit_account_name` varchar(64) NOT NULL DEFAULT '' COMMENT '赎回账号名称',
  `adv_account` varchar(32) NOT NULL DEFAULT '' COMMENT '垫资账号',
  `adv_cust_id` bigint(20) NOT NULL COMMENT '垫资客户号',
  `adv_account_name` varchar(64) NOT NULL DEFAULT '' COMMENT '垫资账户名称',
  `charge_account` varchar(32) NOT NULL DEFAULT '' COMMENT '手续费管理费分配账号',
  `share_class` varchar(1) DEFAULT NULL COMMENT '收费方式 A-前端收费;B-后端收费',
  `is_need_charge` varchar(1) NOT NULL DEFAULT '0' COMMENT '产品是否需要手续费: 0-不需要; 1-需要',
  `is_night_market` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否夜市产品:0否 1是',
  `json_param` varchar(250) NOT NULL DEFAULT '' COMMENT '备用字段',
  `created_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '修改人',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_prd_code` (`prd_code`, `ta_code`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8 ROW_FORMAT = COMPACT COMMENT = '产品信息表';

CREATE TABLE `sfm_ta_prd_daily` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '物理主键',
  `iss_date` int(11) NOT NULL DEFAULT '0' COMMENT '净值日期',
  `cfm_date` int(11) NOT NULL DEFAULT '0' COMMENT '确认日期',
  `ta_code` varchar(9) NOT NULL DEFAULT '' COMMENT 'TA代码',
  `prd_code` varchar(20) NOT NULL DEFAULT '' COMMENT '产品代码',
  `nav` decimal(20,9) NOT NULL DEFAULT '0.000000000' COMMENT '产品净值',
  `seven_rate` decimal(28,8) NOT NULL DEFAULT '0.00000000' COMMENT '七日年化收益率',
  `tenth_income` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '万份单位收益',
  `prd_status` varchar(1) NOT NULL DEFAULT '' COMMENT '产品状态',
  `tot_nav` decimal(20,9) NOT NULL DEFAULT '0.000000000' COMMENT '产品累计净值',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_prd_daily` (`iss_date`,`ta_code`,`prd_code`,`cfm_date`) USING BTREE,
  KEY `idx_prd_code_date` (`prd_code`,`iss_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='产品行情表';
